apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-cron
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the kubernetes cluster
          restartPolicy: OnFailure
  schedule: "*/1 * * * *"